### ISSUE TITLE
Coordinates _top and _bottom fail when cell becomes too vertical

### ISSUE THREAD

**Issue by azagajewski** [Jhsmit/ColiCoords#119]
Great work, currently using in my research!

When working with cells that are more vertical we found the calculation of the circumference (Cell.circumference) fails and returns a NaN. Looking into it, we found that's because the integrals in the Coordinates._top and _bottom methods diverge for such conditions - maybe a small bug in the analytic expression of the arc length integrand.

Attached is an example bitmap of a failing cell. To reproduce fully, initialise a cell over it with the following parameters:

{'xl': 9.052183818572, 'xr': 16.473663643227702, 'a0': 75.8840251535968, 'a1': -4.77838056145959, 'a2': 0.03780895333655627, 'r': 7.0710678118654755, 'shape': (45, 26)}

[exmaple_failing_cell.zip](https://github.com/Jhsmit/ColiCoords/files/6744516/exmaple_failing_cell.zip)

Opened a pull request with a fix to this issue, consider merging!

**Comment by Jhsmit** [comment]
Hi, thanks for bringing this to my attention (and providing the solution!)

In ColiCoords I assume in most of these calculations that the cell is oriented horizontally. There are other calculations, such as the optimization of the coordinate system, that are likely to also go wrong when the cells are oriented vertically. Therefore in most use cases its is recommended that you orient the cells horizontally by using the `data_to_cells` method:

```python
import mahotas as mh
import numpy as np
from colicoords import Data, data_to_cells
from colicoords.plot import CellPlot

img = np.expand_dims(mh.imread('exmaple_failing_cell.bmp'), 0)  # Stack of images is required for `data_to_cells`

data = Data()
data.add_data(img, 'binary')

cell_list = data_to_cells(data, remove_bordering=False, remove_multiple_cells=False)
cell = cell_list[0]
print(cell.circumference)
cp = CellPlot(cell)
cp.imshow('binary')
cp.plot_outline()
cp.show()
``` 
`> 96.18510826633593`

![image](https://user-images.githubusercontent.com/7881506/124257006-363ddd00-db2c-11eb-9ece-7309afe8d7a6.png)


This is slightly different than the value of 102.94616854654704 I get when I use the coordinate parameters you've supplied:

```python
import mahotas as mh
from colicoords import Data, Cell
from colicoords.plot import CellPlot

img = mh.imread('exmaple_failing_cell.bmp')

data = Data()
data.add_data(img, 'binary')

parameters = {'xl': 9.052183818572, 'xr': 16.473663643227702, 'a0': 75.8840251535968, 'a1': -4.77838056145959, 'a2': 0.03780895333655627, 'r': 7.0710678118654755, 'shape': (45, 26)}
cell = Cell(data, init_coords=False, **parameters)

print(cell.circumference)
cp = CellPlot(cell)
cp.imshow('binary')
cp.plot_outline()
cp.show()
```
![image](https://user-images.githubusercontent.com/7881506/124256849-0a225c00-db2c-11eb-8b7a-d84d977c5490.png)

Which is to be expected since rotation of binary images modifies the pixels somewhat and the coordinate system is not optimized.

When you only have  a binary image I think the most accurate results are achieved by using `data_to_cells` and then running `cell_list.optimize()`. This gives 97.41 as circumference:

![image](https://user-images.githubusercontent.com/7881506/124257472-af3d3480-db2c-11eb-8ae3-da9e871d52ce.png)

**Comment by azagajewski** [comment]
No worries! Nice to see ColiCoords still being maintained and active! It's very well written which makes finding and fixing issues much easier - very happy to contribute!

In my particular use case I'm trying to avoid interpolation (which horizontal alignment would require), hence I've been seeing those issues. You're right - the vertical cells also pose some issues in the radial distribution calculation (although actual optimization works well). I've tracked it down to a single bug and fixed, now it works flawlessly for all cells. Gonna make a PR with the fix in a minute!
