### ISSUE TITLE
Image analysis

### ISSUE THREAD

**Issue by Nico-F3** [Jhsmit/ColiCoords#125]
Hello,

I have an image that it has a couple of cells in it, which I am trying to analyzed with colicoords. Is  there a way to analyse the whole image and then take an average of the fluorescence and which part of the average of the bacteria is more fluorescent that another ? 

The examples are all of stackts images whichs is not the case for me.

here is the image
![fluo](https://user-images.githubusercontent.com/60949653/130639852-9e9a1076-69c7-42a5-ab8c-e12dda919873.jpg)

thank you in advance,

Nico.

**Comment by Jhsmit** [comment]
Hi Nico, 

Thanks for your post. I'm not sure I fully understand what you're trying to do so perhaps you can provide a bit more information. 
Do you want to analyze the data on a per cell basis? In that case you'll also need a binary image where the cells are segmented.

Can you clarify a bit more what you mean by 'which part of the average of the bacteria is more fluorescent that another?

**Comment by Nico-F3** [comment]
Hello,

Yes, I also have the image as a binary, which I attached to this message.  

My idea is to obtain the fluorescence distribution of each cell and then do an average of each cell to see if there is a pattern. For example, the poles have more intensity than the rest of the cell. Hopefully, this will clarify my question a little more. If not, please tell me, I will try to be more clear.

![binary](https://user-images.githubusercontent.com/60949653/130642372-a7f14d30-fb9c-429b-9074-cf57413c2fe4.jpg)

**Comment by Jhsmit** [comment]
Yes, I understand your question now. 
This is possible and i think what you're looking for is the 'longitudinal distribution'. This averages the fluorescence along the midline of each cell within a certain distance from the midline (see the [docs ](https://colicoords.readthedocs.io/en/latest/modules.html#colicoords.plot.CellListPlot.plot_l_dist)how to control this).

If i look at your images it seems by eye that that indeed more fluorescence is localized at the poles and this can be seen in the longitudinal distribution to some extend, as intensity increases towards the poles (which are at 0 and 1 respectively). The intensity drops after the poles because the cell tapers off there. 

You might want try to use some kind of peak finding on your data and analyze the positions of those peaks with colicoords. We did something similar for a recent publication (see the biorxiv paper [here](https://www.biorxiv.org/content/10.1101/2020.11.20.391094v2)). I'll see if can make the code available for the analysis we did there, if I remember correctly that was a fun one because we had >10000 single cells analyzed.

Here is the code I used to get the longitudinal distributions.  I'm summing the rgb channels of the .jpg images you provided here, I think for the fluorescence this introduces some artifacts but I'm assuming you have single-channel images?

```python
#%%

import numpy as np
import mahotas as mh
from colicoords import Data, data_to_cells, filter_binaries
from colicoords.plot import CellListPlot
import matplotlib.pyplot as plt
import matplotlib

#%%

img = mh.imread('binary.jpg')
img = img.sum(axis=2)  # Sum rgb channels
binary_stack = np.expand_dims((img < 255/2).astype(int), 0)  # convert to binary dtype and to stack

# you might want to tweak parameters here to get the single-cells you want
binary_filtered = filter_binaries(binary_stack, min_size=100)

#%%
img = mh.imread('fluorescence.jpg')
img = img.sum(axis=2)  # Sum rgb channels
flu_stack = np.expand_dims(img, 0)  # convert to binary dtype and to stack

#%%
# View which cells you have left over after filtering (on a black background)
binary_plot = binary_filtered[0].copy().astype(float)
binary_plot[binary_plot == 0.] = np.nan
cmap = matplotlib.cm.get_cmap('jet')
cmap.set_bad('k')
plt.imshow(binary_plot, interpolation='nearest', cmap=cmap)
plt.show()
#%%

data = Data()
data.add_data(binary_filtered, 'binary')
data.add_data(flu_stack, 'fluorescence')

cells = data_to_cells(data)
cells.optimize()  # if you have brightfield images available this will give a more accurate coordinate system

print(len(cells))

clp = CellListPlot(cells)
fig, ax = plt.subplots()
ax.axvline(0, color='k')
ax.axvline(1, color='k')
clp.plot_l_dist(ax)
plt.show()
```

Output:

![filtered_binary](https://user-images.githubusercontent.com/7881506/130652784-eae988ac-0a72-4d5a-b19a-f97e8c0dfa35.png)
![l_dist](https://user-images.githubusercontent.com/7881506/130652808-1803d8ad-0999-4331-a659-e8cd248ebbed.png)

**Comment by Nico-F3** [comment]
Hello @Jhsmit,

This is exactly what I was looking for. I will try and replicate the code locally and read the documentation thoroughly to understanding it better. 

Also, I will read the paper that you cited here to see how you use it. And, when available, see the code. It would begreat to have the code to find the peaks!

Yes, I am using a single-channel image.

Also, if I would like to add the bright field how should I write it ?


something like:

```
`#%%
img = mh.imread(bright.jpg')

img = img.sum(axis=2) 

bright_stack = np.expand_dims(img, 0)`
```

**Comment by Jhsmit** [comment]
Yes, if your brightfield is a .jpg image. Otherwise load your .tiff file and then you dont need the `img.sum(axis=2)`
And if you have that add it to the data object with `data.add_data(bright_stack , 'brightfield')` and then you can do `cells.optimize('brightfield')`
(my previous post had that lime commented out which I've corrected now)

**Comment by Nico-F3** [comment]
This is fantastic,

I will use this and add the peak finder to compare the mean values!

**Comment by Nico-F3** [comment]
To obtain the graph of the longitudinal intensity is there any modification of the data?

I am trying to analyze the data of each cell to then calculate the mean of each point to find the peaks of the average intensity and my result are similar. 

If I plot the mean + the std I obtain a rather flat curve. 

![l_dist](https://user-images.githubusercontent.com/60949653/130796468-578d61ed-c7bc-467d-a658-7e4faeec2214.png)

**Comment by Jhsmit** [comment]
Can you share the code you've used to get that graph?

**Comment by Nico-F3** [comment]
yes and also the data that I used.

`
```
x=cells[0].l_dist(100,data_name='',norm_x=True)# I use this to obtain the normalize cell lenght

array=[]# save the normalize cell lenght in a list
for i in x[0]:
    array.append(i)

from scipy.signal import find_peaks


cells_list=[]#create a list where I will save all the intensities for each cell
i=0
while i < len(cells):
    y=cells[i].l_dist(100,norm_x=True)
    cells_list.append(y[1])
    print(y[1])
    i=i+1
    
   
cells_array = np.array(cells_list)#transform cell into an array
cells_mean=cells_array.mean(axis=0) #obtain the mean intensity for each position of the cell
cells_sd=cells_array.std(axis=0)##obtain the std intensity for each position of the cell

plt.plot(array,cells_mean,'-k')
plt.fill_between(array, cells_mean-cells_sd, cells_mean+cells_sd)
plt.ylim([0,120])
plt.show()`
```

[cells_array.csv](https://github.com/Jhsmit/ColiCoords/files/7047369/cells_array.csv)

**Comment by Jhsmit** [comment]
I've upload the data and code for our 2021 JMB paper: https://github.com/Jhsmit/T3SS-paper
It shows how to do all data processing steps leading to a final dataset of almost 25000 single cells.

The code is a bit messy and confusing and hard to read, feel free to post make an issue in that repository if you have any questions.

I'm closing the discussion here
