### ISSUE TITLE
Docs for chained minimization is wrong

### ISSUE THREAD

**Issue by pckroon** [Jhsmit/ColiCoords#74]
Hey,

the documentation contains the following:
> The minimizers can be chained together to first do a course optimization followed by global optimization:
```python
cell.optimize('brightfield', minimizer=[Powell, DifferentialEvolution])
```

However, this is pointless, since DIfferentialEvolution does not take or use the initial guess generated by Powell. The other way around would be marginally more sensible (Powell also won't find the minimum). Instead, either pass DE the `polish=True` option (see scipy docs), or terminate DE before it's converged to find a point in the global minimum well, and then optimize using something halfway decent, such as BFGS.

Cheers.

PS. What I'm doing here? I got curious on what you're doing, and the alternative is writing my thesis...

**Comment by Jhsmit** [comment]
Whoo, an actual issue :) Welcome!

Good catch. I was indeed wondering if the result from powell got passed to DifferentialEvolution as initial guesses. But if both operate independently, what is the point of chained minimizers? Or should I do the passing of initial guesses myself?

My reasoning for the chained minimizer was that the differential evolution would have less work because the initial guesses are better.

According to the scipy docs `polish=True` by default with L-BFGS-B as optimizer.

**Comment by pckroon** [comment]
The initial guesses do get passed along to the next minimizer, but DE doesn't use initial guesses (because it's a *global* minimizer). And neither does basinhopping.
I know the default is True, but I can't remember whether symfit overrides that.
